"""
Django settings for simple_project project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qiu)c0s11^i84*!kvaw(si@p8&hsgemgr7*_cthasrmlfrjl-q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

SITE_ID = 1

INSTALLED_APPS = (
    'taggit',
    'ip_limiter',
    'ckeditor',
    'ckeditor_uploader',
    'blog',
    'search',
    'my_hlju',
    # 'haystack',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'simple_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates/")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'simple_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'hlju': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hlju',
        'USER': '',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': 3306,
    }
}

DATABASE_APPS_MAPPING = {
    'blog': 'default',
    'search': 'hlju',
    'ip_limiter': 'hlju',
}

DATABASE_ROUTERS = ['simple_project.database_router.DatabaseAppsRouter']



CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/home/ling/django_cache',
        'TIMEOUT': 600,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    },
    # 'connection-errors': {
    #     'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
    #     'LOCATION': '/home/ling/django_cache_error',
    #     'TIMEOUT': 600,
    #     'OPTIONS': {
    #         'MAX_ENTRIES': 1000
    #     }
    # },
}
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

FILE_CHARSET = 'utf-8'

DEFAULT_CHARSET = 'utf-8'

LANGUAGE_CODE = 'zh-CN'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# Media files
MEDIA_URL = '/uploader/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Email setting
EMAIL_HOST = 'smtp.163.com'  # 163邮箱
EMAIL_HOST_USER = 'your_account'
EMAIL_HOST_PASSWORD = 'your_password'
EMAIL_PORT = 25

# Searching
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.solr_backend.SolrEngine',
        'URL': 'http://127.0.0.1:8983/solr/blog/'
    },
}

HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

# Ckeditor settings
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_JQUERY_URL = 'js/jquery.min.js'
CKEDITOR_IMAGE_BACKEND = 'pillow'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbarGroups': [
            {'name': 'tools'},
		    {'name': 'basicstyles', 'groups': [ 'basicstyles', 'cleanup' ]},
		    {'name': 'styles'},
		    {'name': 'others'},
        ],
        # 'extraPlugins': 'markdown',
        "removeButtons": "Underline,Subscript,Superscript",
        "autoParagraph": False,
        "removeDialogTabs": "image:advanced;link:advanced",
        "enterMode": '2',
        "startupMode": 'source',
    }
}